### ISSUE TITLE
Application doesn't seem to be compatible with Diego ...

### ISSUE THREAD

**Issue by ptitzler** [christiancompton/backup-cloudant#1]
... due to the dependency on environment variables `VCAP_APP_HOST` and  `VCAP_APP_PORT` as outlined in the _known issues_ section at  https://console.ng.bluemix.net/docs/manageapps/depapps.html#migrateapp.

**Comment by christiancompton** [comment]
Good catch @ptitzler!  I'll have a fix tomorrow to account for these changes.

**Comment by christiancompton** [comment]
This issue has been addressed - the application is now Diego compatible.
